"""add a password column

Revision ID: 141e2e468632
Revises: b647724ceca0
Create Date: 2019-02-17 08:56:27.855305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141e2e468632'
down_revision = 'b647724ceca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writer', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writer', 'pass_secure')
    # ### end Alembic commands ###
