"""remove picture column

Revision ID: 21e17e10cbff
Revises: d2c218be4ac9
Create Date: 2019-02-18 13:07:12.406913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e17e10cbff'
down_revision = 'd2c218be4ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writer', 'profile_pic_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writer', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
