"""create name column

Revision ID: 731ff3f4b3ee
Revises: 6868396ea450
Create Date: 2019-02-19 10:44:58.920225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731ff3f4b3ee'
down_revision = '6868396ea450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_writer_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'writer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('writer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_writer_id_fkey', 'comments', 'writer', ['writer_id'], ['id'])
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'name')
    # ### end Alembic commands ###
