"""add a writer table with 1:M relationship

Revision ID: b647724ceca0
Revises: f8c77adcf84a
Create Date: 2019-02-17 08:53:28.637644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b647724ceca0'
down_revision = 'f8c77adcf84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writer_email'), 'writer', ['email'], unique=True)
    op.add_column('users', sa.Column('writer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'writer', ['writer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'writer_id')
    op.drop_index(op.f('ix_writer_email'), table_name='writer')
    op.drop_table('writer')
    # ### end Alembic commands ###
