"""create timestamp column

Revision ID: b9bf81696e81
Revises: 8f495b686561
Create Date: 2019-02-18 20:15:48.421318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bf81696e81'
down_revision = '8f495b686561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_blogs_timestamp'), 'blogs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_timestamp'), table_name='blogs')
    op.drop_column('blogs', 'timestamp')
    # ### end Alembic commands ###
