"""change password column text

Revision ID: c8b3199c1b25
Revises: 141e2e468632
Create Date: 2019-02-17 21:34:59.702118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b3199c1b25'
down_revision = '141e2e468632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writer', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_column('writer', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writer', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('writer', 'password_hash')
    # ### end Alembic commands ###
