"""Initial Migration

Revision ID: d2c218be4ac9
Revises: c8b3199c1b25
Create Date: 2019-02-18 11:08:12.070314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c218be4ac9'
down_revision = 'c8b3199c1b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writer', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writer', 'profile_pic_path')
    # ### end Alembic commands ###
